2.15
annai-inc/drupal-developers-recipe-stokuda pull request #20
Opened 2023-05-28 09:35 UTC by stqp

2023-05-30 09:19 UTC, kyk requested changes
一点コメントしました

2023-05-31 00:30 UTC, stqp commented on web/modules/custom/hello_world/src/Controller/HelloWorldController.php
> +    }
@kyk 
%3 は [ここ](https://github.com/annai-inc/drupal-developers-recipe-stokuda/pull/20/files#diff-0f7774f39081315a9ad3b46e68ca1da25263ef311381c7dfc974bbaca950c988R72) で行っていましたが、ご指摘はもっと別の意味だったでしょうか。

2023-06-02 08:07 UTC, stqp commented on web/modules/custom/hello_world/src/Controller/HelloWorldController.php
> +    }
（メモ）指摘は上記であっていた。再度今さんにレビューして頂けるとのこと。

2023-06-05 07:40 UTC, kyk approved these changes
LGTM :+1:

2023-06-21 11:47 UTC, merged